# Generated by Django 4.2.3 on 2023-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
